project:
  type: website
  output-dir: docs


execute:
  freeze: auto  # re-render only when source changes
  warning: false
  message: false

website:
  title: "Obesity phase 2"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Data Cleaning & Exploratory Data Analysis"
        menu:
          - text: "Exploring the CQPWeb data"
            href: "100_data_cleaning_scripts_EDA/01_ExploreCQPwebData.qmd"
          - text: "Exploring Spacy-generated annotations"
            href: "100_data_cleaning_scripts_EDA/02_ExploreSpacyData.qmd"
      - text: Analysis
        menu:
          - text: "Condition vs Person-first language"
            href: 400_analysis/01_condition_person_first.qmd
          - text: "Use of 'obese'"
            href: 400_analysis/02_obese.qmd
          - text: "Use of 'overweight'"
            href: 400_analysis/03_overweight.qmd
          - text: "Use of 'fat' in a negative context"
            href: 400_analysis/04_fat.qmd
          - text: "Counts vs frequency simulation"
            href: 400_analysis/05_ShowcaseCounts.html

    right:
      - text: "Scope"
        href: 000_scoping/scoping.qmd
      - about.qmd
  repo-url: https://github.sydney.edu.au/informatics/PIPE-3034-obesity2/
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  page-footer:
    center: "Copyright 2022, Darya Vanichkina, Sydney Informatics Hub"

about:
  template: solana

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly
    toc-depth: 2
    code-link: true
    code-fold: true
    highlight-style: github
    crossref:
      fig-title: Figure
      tbl-title: Table


