---
title: "PIPE-3034: Obesity stigma analysis with pattern frequency over time and publication"
author: "Monika Bednarek, Carly Bray, Joel Nothman, Darya Vanichkina"
date: "01/03/2022"
---

[Scope link, Sharepoint Usyd](https://unisyd.sharepoint.com/:w:/t/SydneyInformaticsHub2/Eb2HaGckqAdMtD80k27xdhwBGpKDLwrTfxZuqYGIs0IYSQ?e=cFiVOs)

## 1. Project details

-   Clients: Monika Bednarek
-   Faculty: FASS
-   Collaborators and their affiliations: Carly Bray (USyd PhD Student), Tara (Lancaster),

## Project scoping details

-   Scope prepared by Joel Nothman, Feb 2022
-   Project manager - Marius Mather

## 2. Project summary

### Research context

-   In PIPE-1951, SIH supported Monika to prepare a corpus for studying mentions of obesity in Australian media. As a collaboration with the Obesity Collective, the project hopes to understand the changing nature of reference to obesity over time and publication, with a focus on stigma.

### Client needs

-   This project will create one or more notebooks for inclusion in the Australian Text Analytics Platform (ATAP) library. The notebooks will support the analysis of language trends for this specific project, with components that are reusable for other research, and guidance in the notebook on how the components might be reapplied.

-   The raw language data will not be available in full to the notebooks. Rather, Monika and her RAs will investigate patterns of interest and construct cross-tabulations of their frequency by publication year and source publication. This project will implement visualisation of comparisons across publications and trends over time, and tools for estimating trends and other significant variation.

-   Analysis may also take into account typical political and organisation affiliation of news sources.

-   While this project will primarily deal with already quantified phenomena, the linguistic context will have bearing in relation to:

    -   The choice of statistic, e.g. absolute or relative frequencies; term frequencies vs document frequencies.
    -   The comparison of statistics when linguistic features are considered as "alternatives" or part of "confusion sets" (e.g. comparing the frequency of stigmatising and non-stigmatising variants).
    -   These statistics will represent the number of mentions of a phenomenon across the entire corpus. For example, counts of "lazy" mentioned in the context of "obes\*" will be provided for each (source, year). Outside of the notebook, close analysis will have been applied to estimate, on a sample, the proportion of "lazy" references that are stigmatising of obesity. Applying the assumption that this proportion is invariant with respect to source and year, we will want to estimate the overall quantity of stigmatizing uses.
    -   The interpretation of the results and their impact on further analysis.

### Current data

-   26,163 articles (16M tokens) in text format with metadata in spreadsheet, acquired from LexisNexis. Covers 2008 to 2019 in 10 publications and 2014 to 2019 in 2 publications

## 3. Project Implementation

### Project plan

-   \[negligible time\] Create or use a repository configured with continuous notebook compilation (cf. ATAP notebook repo,, currently private) 

-   \[1 weeks\] Implement initial code to visualise and summarise key features of a cross-tabulation 

-   \[1.5 weeks\] Research and implement variant analyses for 

    -   term and document frequency 

    -   relative and absolute frequency 

    -   comparative frequency within confusion sets 

-   \[1.5 week\] Iterative improvement to the above; Support the researcher to interpret results 

-   \[1 weeks\] Prepare notebook for publication and reuse 

    -   Report on key findings. 

    -   Describe usage in other contexts, within the notebook. 

    -   Include demonstration of computing a contingency table from a DataFrame of texts and metadata. 

### Resources required

-   Statistics, analytics, visualisation
-   Familiarity with text analytics

### Scheduling

-   Client and RA will be available for fortnightly meetings.

### Deliverables

-   Analysis
-   Reusable notebooks

### Exit conditions

-   Work will be completed to budget.

### Out of scope

-   Work beyond time scoped without rebudgeting.

-   Writing to paper.

### Communication plan

-   Fortnightly meetings, ad-hoc communication by email.

-   Data is on RDS.

### Maintenance plan

-   Notebooks delivered on GitHub.com with dependencies specified, lodged with ATAP.

Total budget: 4 weeks FTE effort towards LDaCA RDC 
